(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const types={department_added:'Добавлено в перечень',department_removed:'Убрано из перечня',department_retained:'Сохранено в перечне',reorganization:'Реорганизация',function_loss:'Возможная потеря',function_transfer:'Передача функции',duplication:'Дублирование',conflict:'Конфликт интересов',contradiction:'Противоречие формулировок'};
  const statuses={unknown:'Недостаточно данных',risk:'Возможный риск',confirmed:'Подтверждено фрагментом',dismissed:'Отклонено аналитиком'};
  let files={before:null,after:null}, result=null, busy=false;
  let config={base:'https://api.openai.com/v1',model:'gpt-4.1-mini',key:''};
  function setFiles(side,file){files[side]=file;$(side+'-name').textContent=file?.name||'Документ не выбран';$(side+'-size').textContent=file?`${(file.size/1024).toFixed(0)} КБ · DOCX`:'DOCX · до 10 МБ';result=null;$('results').hidden=true;$('empty-state').hidden=false;}
  for(const side of ['before','after']) $(side+'-file').addEventListener('change',e=>setFiles(side,e.target.files[0]||null));
  function setBusy(value){busy=value;for(const id of ['run','load-example','before-file','after-file','use-ai','settings-open']) $(id).disabled=value;$('run').textContent=value?'Идёт сравнение…':'Сравнить документы';}
  function openSettings(){$('api-base').value=config.base;$('api-model').value=config.model;$('api-key').value=config.key;$('settings').showModal();}
  $('settings-open').addEventListener('click',openSettings);
  $('settings-close').addEventListener('click',()=>$('settings').close());
  $('provider').addEventListener('change',()=>{const local=$('provider').value==='local';$('api-base').value=local?'http://127.0.0.1:11434/v1':'https://api.openai.com/v1';$('api-key').value='';});
  $('settings-form').addEventListener('submit',e=>{e.preventDefault();config={base:$('api-base').value.trim(),model:$('api-model').value.trim(),key:$('api-key').value.trim()};$('use-ai').checked=true;$('settings').close();updateMode();});
  function updateMode(){$('connection-note').textContent=$('use-ai').checked?`AI: ${config.model||'модель не выбрана'} · текст будет отправлен в ${config.base}`:'Без модели: поиск кандидатов по текстовым правилам.';}
  $('use-ai').addEventListener('change',()=>{updateMode();if($('use-ai').checked&&!config.model)openSettings();});
  fetch('/api/config').then(r=>r.json()).then(data=>{config.base=data.base;config.model=data.model; if(data.hasKey)$('key-note').textContent='На сервере настроен ключ. Пустое поле использует его. Текст документов отправляется выбранному провайдеру.';updateMode();}).catch(()=>{$('run-status').textContent='Откройте приложение через локальный сервер, указанный в README.';});
  $('load-example').addEventListener('click',async()=>{if(busy)return;setBusy(true);try{const loaded=[];for(const s of window.DOCUMENT_SOURCES){const response=await fetch(s.file);if(!response.ok)throw Error('Исходные документы недоступны.');loaded.push(new File([await response.blob()],s.name,{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}));}for(const [i,side] of ['before','after'].entries()){const transfer=new DataTransfer();transfer.items.add(loaded[i]);$(side+'-file').files=transfer.files;setFiles(side,loaded[i]);}$('run-status').textContent='Загружены реальные редакции 8 и 9. Анализ ещё не выполнялся.';}catch(e){$('run-status').textContent=e.message;}finally{setBusy(false);}});
  const encode=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,data:String(reader.result).split(',')[1]});reader.onerror=()=>reject(Error('Не удалось прочитать файл.'));reader.readAsDataURL(file);});
  $('upload-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;if(!files.before||!files.after)return;for(const file of Object.values(files)){if(!file.name.toLowerCase().endsWith('.docx')||file.size>10000000){$('run-status').textContent='Нужны DOCX размером до 10 МБ.';return;}}setBusy(true);result=null;$('results').hidden=true;$('empty-state').hidden=true;$('run-status').textContent=$('use-ai').checked?'Извлечение пунктов и запрос к модели. Ожидание может занять до двух минут.':'Извлечение пунктов и сравнение текстов…';const started=performance.now();try{const before=await encode(files.before),after=await encode(files.after);const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({before,after,useAI:$('use-ai').checked,config}),signal:AbortSignal.timeout(150000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Ошибка анализа');result=data;result.timestamp=new Date().toISOString();$('run-status').textContent=`Обработка завершена за ${((performance.now()-started)/1000).toFixed(1)} с.`;$('type-filter').value='all';render();}catch(err){$('run-status').textContent=err.name==='TimeoutError'?'Время ожидания истекло. Повторите без AI или проверьте модель.':err.message;$('empty-state').hidden=false;}finally{setBusy(false);}});
  function evidenceButton(side,id){const doc=result[side],p=doc.paragraphs.find(p=>p.id===id);if(!p)return '';return `<button class="excerpt-button" data-side="${side}" data-id="${esc(id)}">${esc(p.text.slice(0,180))}${p.text.length>180?'…':''}<span>Пункт ${esc(p.section||'не указан')} · ${esc(id)} ↗</span></button>`;}
  function render(){if(!result)return;$('results').hidden=false;$('run-method').textContent={rules:'ТЕКСТОВЫЕ ПРАВИЛА · БЕЗ LLM',ai:'AI + ТЕКСТОВЫЕ ПРАВИЛА · ТРЕБУЕТСЯ ПРОВЕРКА',fallback:'AI НЕ ЗАВЕРШЁН · ПОКАЗАНЫ ТЕКСТОВЫЕ КАНДИДАТЫ'}[result.mode];$('warnings').innerHTML=result.warnings.map(w=>`<p class="notice">${esc(w)}</p>`).join('');$('coverage').textContent=`Извлечено: ${result.before.paragraphs.length} абзацев до / ${result.after.paragraphs.length} после. ${result.mode==='ai'?'В модель передан весь извлечённый текст.':'Семантическая полнота не проверена.'}`;renderFindings();renderConclusion();}
  function renderFindings(){
    const filter=$('type-filter').value;
    const findings=result.findings.filter(f=>filter==='all'||(filter==='departments'?(f.type.startsWith('department_')||f.type==='reorganization'):f.type===filter));
    $('finding-count').textContent=`Показано ${findings.length} из ${result.findings.length}`;
    $('findings').innerHTML=findings.length?findings.map(f=>`<tr>
      <td>${esc(f.title)}<p class="finding-explanation">${esc(f.explanation)}</p><div class="method">${f.method==='llm'?'Предложение модели':'Текстовое правило'} · ${esc(f.id)}</div></td>
      <td>${f.before_ids.length?f.before_ids.map(id=>evidenceButton('before',id)).join(''):'<span class="micro">Фрагмент не указан; отсутствие не доказано.</span>'}</td>
      <td>${f.after_ids.length?f.after_ids.map(id=>evidenceButton('after',id)).join(''):'<span class="micro">Соответствие не найдено. Это не доказательство отсутствия функции.</span>'}</td>
      <td>${esc(types[f.type]||f.type)}</td>
      <td><span class="status ${f.status}">${esc(statuses[f.status]||statuses.unknown)}</span><label><span class="micro">${f.reviewed?'Оценка аналитика':'Не проверено человеком'}</span>
      <select data-review="${esc(f.id)}" aria-label="Статус ${esc(f.title)}">${!f.reviewed?'<option value="" selected disabled>Дать оценку</option>':''}${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${f.reviewed&&f.status===k?'selected':''}>${v}</option>`).join('')}</select></label></td>
      </tr>`).join(''):'<tr><td colspan="5">Кандидатов этого типа не найдено. Это не подтверждает отсутствие риска.</td></tr>';
  }
  function conclusionLines(){const reviewed=result.findings.filter(f=>f.reviewed),confirmed=reviewed.filter(f=>f.status==='confirmed'),risks=result.findings.filter(f=>f.status==='risk'&&!f.reviewed||f.reviewed&&f.status==='risk');return [`Проанализированы «${result.before.name}» и «${result.after.name}».`,`Найдено кандидатов: ${result.findings.length}. Проверено аналитиком: ${reviewed.length}. Подтверждено аналитиком: ${confirmed.length}. Возможных рисков: ${risks.length}.`,`Режим: ${result.mode==='ai'?'модель и текстовые правила':result.mode==='fallback'?'резервный поиск по правилам после ошибки AI':'текстовые правила без модели'}.`,`Результаты не гарантируют полного обнаружения потерь, дублирования и конфликтов интересов. Отсутствие находки не доказывает отсутствие риска.`];}
  function renderConclusion(){$('conclusion').innerHTML='<h3>Предварительное заключение</h3>'+conclusionLines().map(l=>`<p>${esc(l)}</p>`).join('')+'<ul>'+Object.entries(types).filter(([type])=>result.findings.some(f=>f.type===type)).map(([type,label])=>`<li>${label}: ${result.findings.filter(f=>f.type===type).length}</li>`).join('')+'</ul>';}
  $('type-filter').addEventListener('change',()=>{if(result)renderFindings();});
  document.addEventListener('change',e=>{const id=e.target.dataset.review;if(!id||!result)return;const item=result.findings.find(f=>f.id===id);if(!e.target.value)return;item.status=e.target.value;item.reviewed=true;renderFindings();renderConclusion();});
  document.addEventListener('click',e=>{const button=e.target.closest('[data-side]');if(!button||!result)return;const doc=result[button.dataset.side],index=doc.paragraphs.findIndex(p=>p.id===button.dataset.id);$('evidence-meta').textContent=button.dataset.side==='before'?'ИСХОДНАЯ РЕДАКЦИЯ':'НОВАЯ РЕДАКЦИЯ';$('evidence-title').textContent='Пункт '+(doc.paragraphs[index].section||'не указан');$('evidence-file').textContent=doc.name+' · SHA-256 '+doc.sha256;$('evidence-body').innerHTML=doc.paragraphs.slice(Math.max(0,index-1),index+2).map(p=>`<p class="${p.id===button.dataset.id?'target':''}">${esc(p.text)}<small>${esc(p.id)} · пункт ${esc(p.section||'не указан')}</small></p>`).join('');$('evidence').showModal();});
  $('evidence-close').addEventListener('click',()=>$('evidence').close());
  $('download').addEventListener('click',()=>{if(!result)return;const lines=['# Предварительное заключение',result.timestamp,'',...conclusionLines(),...result.warnings.map(w=>'Ограничение: '+w),'',`SHA-256 до: ${result.before.sha256}`,`SHA-256 после: ${result.after.sha256}`];for(const f of result.findings){lines.push('',`## ${f.title}`,`Тип: ${types[f.type]}; статус: ${statuses[f.status]}; ${f.reviewed?'оценка аналитика':'не проверено человеком'}; метод: ${f.method}`,f.explanation);for(const side of ['before','after']){const doc=result[side];for(const id of f[side+'_ids']){const p=doc.paragraphs.find(p=>p.id===id);lines.push(`Источник: ${doc.name}, п. ${p.section||'не указан'}, ${id}`,`> ${p.text}`);}}}const url=URL.createObjectURL(new Blob([lines.join('\n\n')],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='zaklyuchenie.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
})();
